Arm subsystem
team467/Robot-Code pull request #151
Opened 2024-02-02 21:51 UTC by admlvntv

2024-02-05 20:34 UTC, Aradig26 commented on src/main/java/frc/robot/subsystems/arm/ArmIOSparkMAX.java
Move motor ids to constants file

2024-02-06 00:11 UTC, EQMoore requested changes

2024-02-06 00:11 UTC, EQMoore commented on src/main/java/frc/robot/RobotContainer.java
> +          arm = new Arm(new ArmIOSparkMAX());
Remove this

2024-02-06 00:47 UTC, EQMoore requested changes

2024-02-06 00:47 UTC, EQMoore commented on src/main/java/frc/robot/subsystems/arm/ArmConstants.java
> +      horizontalOffset; // position between our 0 (neutral pick up position) and real 0 (parallel to
this should be HORIZONTAL_OFFSET

2024-02-08 01:10 UTC, EQMoore approved these changes
LGTM

2024-02-08 01:21 UTC, merged