2024 shooter
team467/Robot-Code pull request #153
Opened 2024-02-03 01:48 UTC by EQMoore

2024-02-03 18:15 UTC, admlvntv requested changes
A few changes need to be made, mostly removing remnants of stuff from your testing

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +  }
just have this run the manualShoot method with a value of 0.0

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +      return shooterFeedack.atSetpoint();
make sure that in your constructor you define what the tolerance is, or this will always return true or false I forget

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +    return Math.hypot(211.0, distanceFromSpeaker);
what is this constant? make it a static final variable and put it at the top of the class

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +    return Math.abs(Math.atan(211.0 / distanceFromSpeaker));
ditto

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/ShooterConstants.java
> +      }
get rid of these

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/ShooterConstants.java
> +        SHOOTER_2_ID = 3;
default to 0.

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/ShooterConstants.java
> +        SHOOTER_2_ID = 1;
these should be in Schematic.java

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/ShooterIOPhysical2.java
remove either one or two

2024-02-03 18:15 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/ShooterIOSim.java
this class seems super out of date. either update it or remove it

2024-02-06 01:23 UTC, Aradig26 requested changes

2024-02-06 01:23 UTC, Aradig26 commented on src/main/java/frc/robot/subsystems/shooter/ShooterIOClark.java
> +    inputs.shooterLeaderAppliedVolts = shooterLeader.getAppliedOutput();
multipy by getBusVolts

2024-02-06 01:23 UTC, Aradig26 commented on src/main/java/frc/robot/subsystems/shooter/ShooterIODillion.java
> +    inputs.shooterLeaderAppliedVolts = shooter.getAppliedOutput();
multipy by getBusVolts

2024-02-06 01:27 UTC, admlvntv requested changes
more fixes!

2024-02-06 01:27 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/indexer/IndexerConstants.java
> +/** Add your docs here. */
oops

2024-02-06 01:27 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/indexer/IndexerIO.java
> +/** Add your docs here. */
oops

2024-02-06 01:27 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/indexer/IndexerIOPhysical.java
> +    indexerEncoder.setPositionConversionFactor(rotsToMeters);
these should be the same units, radians

2024-02-06 01:27 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +    return Commands.run(() -> io.setShooterVoltage(volts), this);
set PIDMode = false probably

2024-02-06 01:27 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/ShooterIOClark.java
> +    shooterFollowerEncoder.setVelocityConversionFactor(rotsToRads / 60);
you forgot to set position conversion factor

2024-02-06 01:27 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/ShooterIODillion.java
> +    shooterEncoder.setVelocityConversionFactor(rotsToRads / 60);
ditto

2024-02-07 23:23 UTC, Aradig26 commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +  private double currentVelocitySetpoint;
all caps and height is spelt wrong

2024-02-07 23:28 UTC, Aradig26 approved these changes
LGTM

2024-02-08 00:00 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/indexer/IndexerIOPhysical.java
> +    inputs.indexerLimitSwitchPressed = indexerLimitSwitch.get();
im pretty sure this is negated but idk

2024-02-08 00:02 UTC, admlvntv requested changes
one more thing

2024-02-08 00:02 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +  private PIDController shooterFeedack =
shooterFeed**b**ack

2024-02-08 00:43 UTC, admlvntv approved these changes
lgtm

2024-02-08 00:44 UTC, merged