Shayan renames the shooter thingy
team467/Robot-Code pull request #171
Opened 2024-02-13 01:51 UTC by ShayanHasNo

2024-02-13 01:52 UTC, Aradig26 requested changes
rename branch and commit

2024-02-13 02:02 UTC, EQMoore requested changes
It looks like you have intake changes in this pull request, please remove them as requested.

2024-02-13 02:02 UTC, EQMoore commented on src/main/java/frc/robot/RobotContainer.java
> +import frc.robot.subsystems.intake.IntakeIOPhysical;
remove these imports, besides line 35 (IntakeIO), after you remove all requested references of intake in this file

2024-02-16 13:30 UTC, EQMoore commented on src/main/java/frc/robot/RobotContainer.java
> +    driverController.leftTrigger().whileTrue(intake.intake(driverController.getLeftTriggerAxis()));
Also, why is intake in a shooter pull request?

2024-02-17 00:48 UTC, EQMoore approved these changes
lgtm

2024-02-17 00:57 UTC, Aradig26 approved these changes

2024-02-17 00:57 UTC, merged