Climber fixes
team467/Robot-Code pull request #182
Opened 2024-02-24 20:22 UTC by EQMoore

Adds solenoid to climber and puts updateInputs in periodic

2024-02-24 21:56 UTC, ShayanHasNo reviewed
LGTM too me but get someone else to double check

2024-02-26 20:07 UTC, Aradig26 approved these changes
LGTM

2024-02-26 21:05 UTC, admlvntv requested changes
One thing

2024-02-26 21:05 UTC, admlvntv commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    climberIO.updateInputs(climberIOInputs);
Make sure to do a processInputs too

2024-02-26 21:06 UTC, Aradig26 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    climberIO.updateInputs(climberIOInputs);
Good catch

2024-03-03 01:11 UTC, EQMoore commented
Changed to NEOs, refer to split climber

2024-03-03 01:11 UTC, closed without merging