Add Arm Subsystem
team467/Robot-Code pull request #42
Opened 2023-02-18 20:08 UTC by JashKotadiya

2023-02-18 20:09 UTC, AdamCraftmaster commented
Needs to pull main

2023-02-18 20:31 UTC, AdamCraftmaster requested changes
A few things to look at

2023-02-18 20:31 UTC, AdamCraftmaster commented on .vscode/settings.json
> +    "editor.defaultFormatter": "mwpb.java-prettier-formatter"
This should not be here, this is for individuals only

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/commands/arm/ArmStopCMD.java
> +    return false; // TODO: arm.isStopped();
Fix this TODO

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/constants/CompBotConstants.java
> +    return 180;
Is this in degrees or radians?

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/constants/RobotArmConstants.java
> +package frc.robot.constants;
This file should be deleted

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/subsystems/arm/Arm.java
> +    logger.recordOutput("Arm/mode", mode.toString());
For this and all other outputs, it should be in UpperCamel case

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/subsystems/arm/ArmIOSim.java
> +package frc.robot.subsystems.arm;
This file should be rewritten or deleted

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/subsystems/conevision/ConeTargetDistance.java
> +package frc.robot.subsystems.conevision;
This file should be deleted

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/Robot.java
> -    // Record metadata
Do not delete metadata, add it back

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/Robot.java
> +          //   new PowerDistribution(63, ModuleType.kRev);
This should be uncommented

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/RobotConstants.java
> +          case "hopper":
This case should be removed

2023-02-18 20:31 UTC, AdamCraftmaster commented on src/main/java/frc/robot/RobotContainer.java
> +    arm =
This should be moved into the cases, in order to ensure that sim ignores it (will fix this in a commit soon)

2023-02-20 18:49 UTC, elleryjh commented on src/main/java/frc/robot/constants/CompBotConstants.java
> +    return 180;
Renamed to indicate meters.

2023-02-23 00:41 UTC, AdamCraftmaster approved these changes
lgtm

2023-02-23 00:46 UTC, merged